/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Osmosis.Heartbeat', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Osmosis.Heartbeat = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Osmosis.Heartbeat, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Osmosis.Heartbeat.displayName = 'proto.Osmosis.Heartbeat';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.Osmosis.Heartbeat.prototype.toObject = function (opt_includeInstance) {
    return proto.Osmosis.Heartbeat.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.Osmosis.Heartbeat} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.Osmosis.Heartbeat.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        appid: msg.getAppid_asB64(),
        peerid: msg.getPeerid_asB64(),
        peername: jspb.Message.getFieldWithDefault(msg, 3, ''),
        port: jspb.Message.getFieldWithDefault(msg, 4, 0),
        publickey: msg.getPublickey_asB64(),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Osmosis.Heartbeat}
 */
proto.Osmosis.Heartbeat.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Osmosis.Heartbeat();
  return proto.Osmosis.Heartbeat.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Osmosis.Heartbeat} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Osmosis.Heartbeat}
 */
proto.Osmosis.Heartbeat.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {!Uint8Array} */ (reader.readBytes());
        msg.setAppid(value);
        break;
      case 2:
        var value = /** @type {!Uint8Array} */ (reader.readBytes());
        msg.setPeerid(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setPeername(value);
        break;
      case 4:
        var value = /** @type {number} */ (reader.readUint32());
        msg.setPort(value);
        break;
      case 5:
        var value = /** @type {!Uint8Array} */ (reader.readBytes());
        msg.setPublickey(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Osmosis.Heartbeat.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.Osmosis.Heartbeat.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Osmosis.Heartbeat} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Osmosis.Heartbeat.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getAppid_asU8();
  if (f.length > 0) {
    writer.writeBytes(1, f);
  }
  f = message.getPeerid_asU8();
  if (f.length > 0) {
    writer.writeBytes(2, f);
  }
  f = message.getPeername();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getPort();
  if (f !== 0) {
    writer.writeUint32(4, f);
  }
  f = message.getPublickey_asU8();
  if (f.length > 0) {
    writer.writeBytes(5, f);
  }
};

/**
 * optional bytes appId = 1;
 * @return {!(string|Uint8Array)}
 */
proto.Osmosis.Heartbeat.prototype.getAppid = function () {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(
    this,
    1,
    ''
  ));
};

/**
 * optional bytes appId = 1;
 * This is a type-conversion wrapper around `getAppid()`
 * @return {string}
 */
proto.Osmosis.Heartbeat.prototype.getAppid_asB64 = function () {
  return /** @type {string} */ (jspb.Message.bytesAsB64(this.getAppid()));
};

/**
 * optional bytes appId = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAppid()`
 * @return {!Uint8Array}
 */
proto.Osmosis.Heartbeat.prototype.getAppid_asU8 = function () {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getAppid()));
};

/** @param {!(string|Uint8Array)} value */
proto.Osmosis.Heartbeat.prototype.setAppid = function (value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};

/**
 * optional bytes peerId = 2;
 * @return {!(string|Uint8Array)}
 */
proto.Osmosis.Heartbeat.prototype.getPeerid = function () {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(
    this,
    2,
    ''
  ));
};

/**
 * optional bytes peerId = 2;
 * This is a type-conversion wrapper around `getPeerid()`
 * @return {string}
 */
proto.Osmosis.Heartbeat.prototype.getPeerid_asB64 = function () {
  return /** @type {string} */ (jspb.Message.bytesAsB64(this.getPeerid()));
};

/**
 * optional bytes peerId = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPeerid()`
 * @return {!Uint8Array}
 */
proto.Osmosis.Heartbeat.prototype.getPeerid_asU8 = function () {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getPeerid()));
};

/** @param {!(string|Uint8Array)} value */
proto.Osmosis.Heartbeat.prototype.setPeerid = function (value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};

/**
 * optional string peerName = 3;
 * @return {string}
 */
proto.Osmosis.Heartbeat.prototype.getPeername = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''));
};

/** @param {string} value */
proto.Osmosis.Heartbeat.prototype.setPeername = function (value) {
  jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional uint32 port = 4;
 * @return {number}
 */
proto.Osmosis.Heartbeat.prototype.getPort = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};

/** @param {number} value */
proto.Osmosis.Heartbeat.prototype.setPort = function (value) {
  jspb.Message.setProto3IntField(this, 4, value);
};

/**
 * optional bytes publicKey = 5;
 * @return {!(string|Uint8Array)}
 */
proto.Osmosis.Heartbeat.prototype.getPublickey = function () {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(
    this,
    5,
    ''
  ));
};

/**
 * optional bytes publicKey = 5;
 * This is a type-conversion wrapper around `getPublickey()`
 * @return {string}
 */
proto.Osmosis.Heartbeat.prototype.getPublickey_asB64 = function () {
  return /** @type {string} */ (jspb.Message.bytesAsB64(this.getPublickey()));
};

/**
 * optional bytes publicKey = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPublickey()`
 * @return {!Uint8Array}
 */
proto.Osmosis.Heartbeat.prototype.getPublickey_asU8 = function () {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
    this.getPublickey()
  ));
};

/** @param {!(string|Uint8Array)} value */
proto.Osmosis.Heartbeat.prototype.setPublickey = function (value) {
  jspb.Message.setProto3BytesField(this, 5, value);
};

goog.object.extend(exports, proto.Osmosis);
